name: ros2-humble-py310
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - alsa-lib=1.2.14
  - ampl-asl=1.0.0
  - aom=3.9.1
  - assimp=5.4.3
  - attr=2.5.2
  - beautifulsoup4=4.13.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - casadi=3.7.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - cli11=2.5.0
  - coal=3.0.1
  - coal-python=3.0.1
  - console_bridge=1.0.2
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.3.1
  - draccus=0.10.0
  - eigen=3.4.0
  - eigenpy=3.12.0
  - elfutils=0.193
  - evdev=1.9.2
  - feedparser=6.0.12
  - ffmpeg=8.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdbm=1.18
  - gdk-pixbuf=2.44.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glslang=15.4.0
  - gmp=6.3.0
  - gnutls=3.8.9
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=11.5.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hpp-fcl=3.0.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imath=3.2.1
  - intel-gmmlib=22.8.2
  - intel-media-driver=25.3.4
  - ipopt=3.14.19
  - iso8601=2.1.0
  - jasper=4.2.8
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.2
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.9.0
  - libblasfeo=0.1.4.2
  - libboost=1.88.0
  - libboost-devel=1.88.0
  - libboost-headers=1.88.0
  - libboost-python=1.88.0
  - libboost-python-devel=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.76
  - libcblas=3.9.0
  - libclang-cpp21.1=21.1.0
  - libclang13=21.1.0
  - libcoal=3.0.1
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libfatrop=0.0.4
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgz-cmake3=3.5.3
  - libgz-cmake4=4.2.0
  - libgz-math7=7.5.2
  - libgz-tools2=2.0.3
  - libgz-utils2=2.2.0
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmicrohttpd=1.0.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopengl=1.7.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libosqp=1.0.0
  - libpciaccess=0.18
  - libpinocchio=3.8.0
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=6.31.1
  - libqdldl=0.1.8
  - librsvg=2.58.4
  - libscotch=7.0.4
  - libsdformat14=14.8.0
  - libsndfile=1.2.2
  - libspral=2025.05.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.9
  - libtasn1=4.20.0
  - libtiff=4.7.1
  - libudev1=257.9
  - libunistring=0.9.10
  - libunwind=1.8.3
  - liburing=2.12
  - libusb=1.0.29
  - libuuid=2.41.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - markupsafe=3.0.2
  - mergedeep=1.3.4
  - metis=5.1.0
  - mpg123=1.32.9
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - mypy_extensions=1.1.0
  - ncurses=6.5
  - nettle=3.10.1
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - octomap=1.10.0
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openldap=2.6.10
  - openssl=3.5.4
  - p11-kit=0.24.1
  - pango=1.56.4
  - pcre2=10.46
  - pinocchio=3.8.0
  - pinocchio-python=3.8.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pure-python-adb=0.3.0.dev0
  - py-opencv=4.12.0
  - pycparser=2.22
  - pynput=1.8.1
  - pyserial=3.5
  - pysocks=1.7.1
  - python=3.10.18
  - python-xlib=0.33
  - python_abi=3.10
  - pyyaml=6.0.2
  - pyyaml-include=1.4.1
  - qhull=2020.2
  - qhull-static=2020.2
  - qt6-main=6.9.2
  - rav1e=0.7.1
  - reader=3.17
  - readline=8.2
  - requests=2.32.5
  - ruby=3.4.5
  - scipy=1.15.2
  - sdl2=2.32.56
  - sdl3=3.2.22
  - sgmllib3k=1.0.0
  - shaderc=2025.3
  - six=1.17.0
  - snappy=1.2.2
  - soupsieve=2.8
  - spirv-tools=2025.1
  - svt-av1=3.1.2
  - tbb=2022.2.0
  - tinyxml2=11.0.0
  - tk=8.6.13
  - toml=0.10.2
  - transforms3d=0.4.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - tzdata=2025b
  - urdfdom=4.0.1
  - urdfdom_headers=1.1.2
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - argcomplete==3.6.2
      - asttokens==3.0.0
      - catkin-pkg==1.1.0
      - colcon-argcomplete==0.3.3
      - colcon-bash==0.5.0
      - colcon-cd==0.1.1
      - colcon-cmake==0.2.29
      - colcon-common-extensions==0.3.0
      - colcon-core==0.20.0
      - colcon-defaults==0.2.9
      - colcon-devtools==0.3.0
      - colcon-library-path==0.2.1
      - colcon-metadata==0.2.5
      - colcon-notification==0.3.0
      - colcon-output==0.2.13
      - colcon-package-information==0.4.0
      - colcon-package-selection==0.2.10
      - colcon-parallel-executor==0.4.0
      - colcon-pkg-config==0.1.0
      - colcon-powershell==0.4.0
      - colcon-python-setup-py==0.2.9
      - colcon-recursive-crawl==0.2.3
      - colcon-ros==0.5.0
      - colcon-test-result==0.3.8
      - colcon-zsh==0.5.0
      - coverage==7.10.7
      - decorator==5.2.1
      - distlib==0.4.0
      - docutils==0.22.2
      - empy==3.3.4
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - iniconfig==2.1.0
      - ipython==8.37.0
      - jedi==0.19.2
      - lark==1.3.0
      - matplotlib-inline==0.1.7
      - meshcat==0.3.2
      - notify2==0.3.1
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - piper-sdk==0.4.2
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyngrok==7.4.0
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - pytest-repeat==0.9.4
      - pytest-rerunfailures==16.0.1
      - python-can==4.6.1
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - setuptools==79.0.1
      - stack-data==0.6.3
      - tomli==2.2.1
      - tornado==6.5.2
      - traitlets==5.14.3
      - u-msgpack-python==2.8.0
      - wcwidth==0.2.14
      - wrapt==1.17.3
