from glob import glob
from setuptools import find_packages, setup

package_name = 'je_software'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages', [f'resource/{package_name}']),
        (f'share/{package_name}', ['package.xml']),
        (f'share/{package_name}/launch', ['launch/orbbec.launch.py']),
        (f'share/{package_name}/config', ['config/orbbec.yaml']),
        (f'share/{package_name}/launch', ['launch/agilex_robot.launch.py']),
        (f'share/{package_name}/launch', ['launch/dynamixel_init_joint_state.launch.py']),
        (f'share/{package_name}/launch', ['launch/tactile_sensor.launch.py']),
        (f'share/{package_name}/launch', ['launch/manager.launch.py']),
        (f'share/{package_name}/launch', ['launch/manager_test.launch.py']),
        (f'share/{package_name}/launch', ['launch/replay_node.launch.py']),
        (f'share/{package_name}/launch', ['launch/jearm_rviz_replay.launch.py']),
        (f'share/{package_name}/launch', ['launch/lh_jearm_moveit.launch.py']),
        (f'share/{package_name}/launch', ['launch/pcb_process_demo.launch.py']),
        (f'share/{package_name}/config', ['config/pcb_process_demo.yaml']),
        (f'share/{package_name}/config/moveit', glob('config/moveit/*')),
        (f'share/{package_name}/rviz', glob('rviz/*')),
        (f'share/{package_name}/urdf', glob('urdf/*')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='kleist',
    maintainer_email='gmvonkleist@gmail.com',
    description='TODO: Package description',
    license='Apache-2.0',
    extras_require={
        'test': [
            'pytest',
        ],
    },
    entry_points={
        'console_scripts': [
            'koch_leader_teleop = je_software.koch_leader_node:main',
            'dynamixel_init_joint_state = je_software.dynamixel_init_joint_state_node:main',
            'camera_node = je_software.camera_node:main',
            'eye_in_hand_calibration = je_software.new_system_architecture.eye_in_hand_calibration_node:main',
            'eye_in_hand_validator = je_software.new_system_architecture.eye_in_hand_validator_node:main',
            'eye_to_hand_calibration = je_software.new_system_architecture.eye_to_hand_calibration_node:main',
            'eye_to_hand_validator = je_software.new_system_architecture.eye_to_hand_validator_node:main',
            'hand_eye_calibration = je_software.new_system_architecture.hand_eye_calibration_node:main',
            'orbbec_intrinsics_validator = je_software.orbbec_intrinsics_validator_node:main',
            'agilex_robot = je_software.robot_node:main',
            'tactile_sensor = je_software.tactile_sensor_node:main',
            'manager_node = je_software.recorder_manager_node:main',
            'test_publisher = je_software.test_publisher_node:main',
            'replay_node = je_software.replay_node:main',
            'jearm_jsonl_replayer_node = je_software.new_system_architecture.jearm_jsonl_replayer_node:main',
            'joint_rate_monitor = je_software.joint_rate_monitor_node:main',
            'terminal_key_signal_node = je_software.new_system_architecture.terminal_key_signal_node:main',
            'fixed_line_vision_node = je_software.new_system_architecture.fixed_line_vision_node:main',
            'fixed_inspection_node = je_software.new_system_architecture.fixed_inspection_node:main',
            'fixed_slot_provider_node = je_software.new_system_architecture.fixed_slot_provider_node:main',
            'zmq_motion_backend_node = je_software.new_system_architecture.zmq_motion_backend_node:main',
            'pcb_process_task_manager_node = je_software.new_system_architecture.pcb_process_task_manager_node:main',
        ],
    },
)
